# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Win/Despair
email: ziadig@gmail.com
description: >
  Chronicles of a journey to financial independence and thoughts on living a meaningful life
url: "https://www.windespair.com" # the base hostname & protocol for your site

# Name of repository, for use with Staticman
repository: "GonzaloZiadi/windespair"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "master"

timezone: America/Phoenix

permalink: /:title/

author-name: 'Gonzalo Ziadi'

author:
  twitter: gziadi

twitter:
  username: gziadi
  card: summary

social:
  name: Gonzalo Ziadi
  links:
    - https://twitter.com/gziadi
    - https://www.linkedin.com/in/GonzaloZiadi
    - https://github.com/GonzaloZiadi

# Build settings
markdown: kramdown

sass:
  style: compressed

include: [_headers]

#compress.html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

reCaptcha:
  enabled: true
  siteKey: "6Lc8XmAUAAAAAOxD-rgHpGa_UTpfYP2Xr0RXoomo"
  secret: "quY62dP/4vEeAaLogCYzT24tm7w2oNX0rmRLfFXiguvoNyUozAxQSA74hOB8TzD7uLTmDijzVVgXGgqr1Ue7quC0geeS0saSZDlXtokfHguuCuYIRBfH6RCsb/3uiTSCU9cBcMp5/P9fjGNG5daA0YJyUG3mGQtbaHBp5viU468="

plugins:
    - jekyll-seo-tag
    - uglifier
