# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WinDespair
email: ziadig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Gonzalo. I write and I code.
url: "https://www.windespair.com" # the base hostname & protocol for your site

# Name of repository, for use with Staticman
repository: "GonzaloZiadi/windespair"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "master"

timezone: US/Eastern

permalink: /:title/

analytics:

# Color schemes
color-1: '#d64242'
color-2: '#a43820'

# Author picture 100x100 --> keep it inside img folder.
author-image: 'author.jpg'
author-name: 'Gonzalo Ziadi'
author-about: 'Keep getting better.'

author:
  twitter: gziadi

twitter:
  username: GZiadi

social:
  name: Gonzalo Ziadi
  links:
    - https://twitter.com/GZiadi
    - https://www.linkedin.com/in/GonzaloZiadi
    - https://github.com/GonzaloZiadi

# Build settings
markdown: kramdown

sass:
    style: compressed

#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

gems: [jekyll-seo-tag]
